# Generated by Django 3.1 on 2020-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('programming', 'Programming'), ('network', 'Network'), ('news', 'News'), ('ebook', 'Ebook'), ('database', 'Database')], max_length=12),
        ),
    ]
